server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:poker-planning
    username: poker
    password: poker
    driverClassName: org.h2.Driver
    mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
  jpa:
    spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect